/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: src/annoygomodule.i



#define SWIG_VERSION 0x040201
#define SWIGGO
#define SWIGMODULE annoy
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NULLPTR nullptr
#else
# define SWIG_NULLPTR NULL
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include "annoygomodule.h"

#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_annoy_db50064239c65d95(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_annoy_db50064239c65d95(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


void _wrap_delete_X_RawAnnoyVectorFloat_annoy_db50064239c65d95(GoAnnoy::AnnoyVectorFloat *_swig_go_0) {
  GoAnnoy::AnnoyVectorFloat *arg1 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_0; 
  
  delete arg1;
  
}


float *_wrap_X_RawAnnoyVectorFloat_ArrayPtr_annoy_db50064239c65d95(GoAnnoy::AnnoyVectorFloat *_swig_go_0) {
  GoAnnoy::AnnoyVectorFloat *arg1 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  float *result = 0 ;
  float *_swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_0; 
  
  result = (float *)(arg1)->ArrayPtr();
  *(float **)&_swig_go_result = (float *)result; 
  return _swig_go_result;
}


intgo _wrap_X_RawAnnoyVectorFloat_Len_annoy_db50064239c65d95(GoAnnoy::AnnoyVectorFloat *_swig_go_0) {
  GoAnnoy::AnnoyVectorFloat *arg1 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_0; 
  
  result = (int)(arg1)->Len();
  _swig_go_result = result; 
  return _swig_go_result;
}


float _wrap_X_RawAnnoyVectorFloat_Get_annoy_db50064239c65d95(GoAnnoy::AnnoyVectorFloat *_swig_go_0, intgo _swig_go_1) {
  GoAnnoy::AnnoyVectorFloat *arg1 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  int arg2 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (float)(arg1)->Get(arg2);
  _swig_go_result = result; 
  return _swig_go_result;
}


GoAnnoy::AnnoyVectorFloat *_wrap_new_X_RawAnnoyVectorFloat_annoy_db50064239c65d95() {
  GoAnnoy::AnnoyVectorFloat *result = 0 ;
  GoAnnoy::AnnoyVectorFloat *_swig_go_result;
  
  
  result = (GoAnnoy::AnnoyVectorFloat *)new GoAnnoy::AnnoyVectorFloat();
  *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_result = (GoAnnoy::AnnoyVectorFloat *)result; 
  return _swig_go_result;
}


void _wrap_delete_X_RawAnnoyVectorInt_annoy_db50064239c65d95(GoAnnoy::AnnoyVectorInt *_swig_go_0) {
  GoAnnoy::AnnoyVectorInt *arg1 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_0; 
  
  delete arg1;
  
}


int *_wrap_X_RawAnnoyVectorInt_ArrayPtr_annoy_db50064239c65d95(GoAnnoy::AnnoyVectorInt *_swig_go_0) {
  GoAnnoy::AnnoyVectorInt *arg1 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  int32_t *result = 0 ;
  int *_swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_0; 
  
  result = (int32_t *)(arg1)->ArrayPtr();
  *(int32_t **)&_swig_go_result = (int32_t *)result; 
  return _swig_go_result;
}


intgo _wrap_X_RawAnnoyVectorInt_Len_annoy_db50064239c65d95(GoAnnoy::AnnoyVectorInt *_swig_go_0) {
  GoAnnoy::AnnoyVectorInt *arg1 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_0; 
  
  result = (int)(arg1)->Len();
  _swig_go_result = result; 
  return _swig_go_result;
}


int _wrap_X_RawAnnoyVectorInt_Get_annoy_db50064239c65d95(GoAnnoy::AnnoyVectorInt *_swig_go_0, intgo _swig_go_1) {
  GoAnnoy::AnnoyVectorInt *arg1 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  int arg2 ;
  int32_t result;
  int _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  result = (arg1)->Get(arg2);
  *(int32_t **)&_swig_go_result = new int32_t(result); 
  return _swig_go_result;
}


GoAnnoy::AnnoyVectorInt *_wrap_new_X_RawAnnoyVectorInt_annoy_db50064239c65d95() {
  GoAnnoy::AnnoyVectorInt *result = 0 ;
  GoAnnoy::AnnoyVectorInt *_swig_go_result;
  
  
  result = (GoAnnoy::AnnoyVectorInt *)new GoAnnoy::AnnoyVectorInt();
  *(GoAnnoy::AnnoyVectorInt **)&_swig_go_result = (GoAnnoy::AnnoyVectorInt *)result; 
  return _swig_go_result;
}


void _wrap_delete_AnnoyIndex_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_AnnoyIndex_addItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, intgo _swig_go_1, _goslice_ _swig_go_2) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  int arg2 ;
  float *arg3 = (float *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_2.array;
  for (int i = 0; i < _swig_go_2.len; i++) {
    w.push_back(v[i]);
  }
  arg3 = &w[0];
  
  
  (arg1)->addItem(arg2,(float const *)arg3);
  
}


void _wrap_AnnoyIndex_build_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, intgo _swig_go_1) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  int arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  (arg1)->build(arg2);
  
}


bool _wrap_AnnoyIndex_save__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  result = (bool)(arg1)->save((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndex_save__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  result = (bool)(arg1)->save((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


void _wrap_AnnoyIndex_unload_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  (arg1)->unload();
  
}


bool _wrap_AnnoyIndex_load__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  result = (bool)(arg1)->load((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndex_load__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  result = (bool)(arg1)->load((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


float _wrap_AnnoyIndex_getDistance_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  int arg2 ;
  int arg3 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  result = (float)(arg1)->getDistance(arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndex_getNnsByItem__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  (arg1)->getNnsByItem(arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndex_getNnsByVector__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  (arg1)->getNnsByVector((float const *)arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndex_getNnsByItem__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  (arg1)->getNnsByItem(arg2,arg3,arg4,arg5);
  
}


void _wrap_AnnoyIndex_getNnsByVector__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  (arg1)->getNnsByVector((float const *)arg2,arg3,arg4,arg5);
  
}


intgo _wrap_AnnoyIndex_getNItems_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  result = (int)(arg1)->getNItems();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndex_verbose_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, bool _swig_go_1) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  bool arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  (arg1)->verbose(arg2);
  
}


void _wrap_AnnoyIndex_getItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, intgo _swig_go_1, GoAnnoy::AnnoyVectorFloat *_swig_go_2) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  int arg2 ;
  GoAnnoy::AnnoyVectorFloat *arg3 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_2; 
  
  (arg1)->getItem(arg2,arg3);
  
}


bool _wrap_AnnoyIndex_onDiskBuild_annoy_db50064239c65d95(GoAnnoy::AnnoyIndex *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndex *arg1 = (GoAnnoy::AnnoyIndex *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndex **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  result = (bool)(arg1)->onDiskBuild((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


GoAnnoy::AnnoyIndex *_wrap_new_AnnoyIndex_annoy_db50064239c65d95() {
  GoAnnoy::AnnoyIndex *result = 0 ;
  GoAnnoy::AnnoyIndex *_swig_go_result;
  
  
  result = (GoAnnoy::AnnoyIndex *)new GoAnnoy::AnnoyIndex();
  *(GoAnnoy::AnnoyIndex **)&_swig_go_result = (GoAnnoy::AnnoyIndex *)result; 
  return _swig_go_result;
}


GoAnnoy::AnnoyIndexAngular *_wrap_new_AnnoyIndexAngular_annoy_db50064239c65d95(intgo _swig_go_0) {
  int arg1 ;
  GoAnnoy::AnnoyIndexAngular *result = 0 ;
  GoAnnoy::AnnoyIndexAngular *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (GoAnnoy::AnnoyIndexAngular *)new GoAnnoy::AnnoyIndexAngular(arg1);
  *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_result = (GoAnnoy::AnnoyIndexAngular *)result; 
  return _swig_go_result;
}


void _wrap_delete_AnnoyIndexAngular_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_AnnoyIndexAngular_addItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, intgo _swig_go_1, _goslice_ _swig_go_2) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  int arg2 ;
  float *arg3 = (float *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_2.array;
  for (int i = 0; i < _swig_go_2.len; i++) {
    w.push_back(v[i]);
  }
  arg3 = &w[0];
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->addItem(arg2,(float const *)arg3);
  
}


void _wrap_AnnoyIndexAngular_build_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, intgo _swig_go_1) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  int arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->build(arg2);
  
}


bool _wrap_AnnoyIndexAngular_save__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->save((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndexAngular_save__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->save((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


void _wrap_AnnoyIndexAngular_unload_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->unload();
  
}


bool _wrap_AnnoyIndexAngular_load__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->load((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndexAngular_load__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->load((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


float _wrap_AnnoyIndexAngular_getDistance_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  int arg2 ;
  int arg3 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (float)(swig_b0)->getDistance(arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndexAngular_getNnsByItem__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByItem(arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndexAngular_getNnsByItem__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByItem(arg2,arg3,arg4,arg5);
  
}


void _wrap_AnnoyIndexAngular_getNnsByVector__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByVector((float const *)arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndexAngular_getNnsByVector__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByVector((float const *)arg2,arg3,arg4,arg5);
  
}


intgo _wrap_AnnoyIndexAngular_getNItems_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (int)(swig_b0)->getNItems();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndexAngular_verbose_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, bool _swig_go_1) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  bool arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->verbose(arg2);
  
}


void _wrap_AnnoyIndexAngular_getItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, intgo _swig_go_1, GoAnnoy::AnnoyVectorFloat *_swig_go_2) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  int arg2 ;
  GoAnnoy::AnnoyVectorFloat *arg3 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getItem(arg2,arg3);
  
}


bool _wrap_AnnoyIndexAngular_onDiskBuild_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexAngular *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexAngular *arg1 = (GoAnnoy::AnnoyIndexAngular *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexAngular **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->onDiskBuild((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


GoAnnoy::AnnoyIndexEuclidean *_wrap_new_AnnoyIndexEuclidean_annoy_db50064239c65d95(intgo _swig_go_0) {
  int arg1 ;
  GoAnnoy::AnnoyIndexEuclidean *result = 0 ;
  GoAnnoy::AnnoyIndexEuclidean *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (GoAnnoy::AnnoyIndexEuclidean *)new GoAnnoy::AnnoyIndexEuclidean(arg1);
  *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_result = (GoAnnoy::AnnoyIndexEuclidean *)result; 
  return _swig_go_result;
}


void _wrap_delete_AnnoyIndexEuclidean_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_AnnoyIndexEuclidean_addItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, intgo _swig_go_1, _goslice_ _swig_go_2) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  int arg2 ;
  float *arg3 = (float *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_2.array;
  for (int i = 0; i < _swig_go_2.len; i++) {
    w.push_back(v[i]);
  }
  arg3 = &w[0];
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->addItem(arg2,(float const *)arg3);
  
}


void _wrap_AnnoyIndexEuclidean_build_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, intgo _swig_go_1) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  int arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->build(arg2);
  
}


bool _wrap_AnnoyIndexEuclidean_save__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->save((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndexEuclidean_save__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->save((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


void _wrap_AnnoyIndexEuclidean_unload_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->unload();
  
}


bool _wrap_AnnoyIndexEuclidean_load__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->load((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndexEuclidean_load__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->load((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


float _wrap_AnnoyIndexEuclidean_getDistance_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  int arg2 ;
  int arg3 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (float)(swig_b0)->getDistance(arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndexEuclidean_getNnsByItem__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByItem(arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndexEuclidean_getNnsByItem__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByItem(arg2,arg3,arg4,arg5);
  
}


void _wrap_AnnoyIndexEuclidean_getNnsByVector__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByVector((float const *)arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndexEuclidean_getNnsByVector__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByVector((float const *)arg2,arg3,arg4,arg5);
  
}


intgo _wrap_AnnoyIndexEuclidean_getNItems_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (int)(swig_b0)->getNItems();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndexEuclidean_verbose_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, bool _swig_go_1) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  bool arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->verbose(arg2);
  
}


void _wrap_AnnoyIndexEuclidean_getItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, intgo _swig_go_1, GoAnnoy::AnnoyVectorFloat *_swig_go_2) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  int arg2 ;
  GoAnnoy::AnnoyVectorFloat *arg3 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getItem(arg2,arg3);
  
}


bool _wrap_AnnoyIndexEuclidean_onDiskBuild_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexEuclidean *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexEuclidean *arg1 = (GoAnnoy::AnnoyIndexEuclidean *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexEuclidean **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->onDiskBuild((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


GoAnnoy::AnnoyIndexManhattan *_wrap_new_AnnoyIndexManhattan_annoy_db50064239c65d95(intgo _swig_go_0) {
  int arg1 ;
  GoAnnoy::AnnoyIndexManhattan *result = 0 ;
  GoAnnoy::AnnoyIndexManhattan *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (GoAnnoy::AnnoyIndexManhattan *)new GoAnnoy::AnnoyIndexManhattan(arg1);
  *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_result = (GoAnnoy::AnnoyIndexManhattan *)result; 
  return _swig_go_result;
}


void _wrap_delete_AnnoyIndexManhattan_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_AnnoyIndexManhattan_addItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, intgo _swig_go_1, _goslice_ _swig_go_2) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  int arg2 ;
  float *arg3 = (float *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_2.array;
  for (int i = 0; i < _swig_go_2.len; i++) {
    w.push_back(v[i]);
  }
  arg3 = &w[0];
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->addItem(arg2,(float const *)arg3);
  
}


void _wrap_AnnoyIndexManhattan_build_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, intgo _swig_go_1) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  int arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->build(arg2);
  
}


bool _wrap_AnnoyIndexManhattan_save__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->save((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndexManhattan_save__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->save((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


void _wrap_AnnoyIndexManhattan_unload_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->unload();
  
}


bool _wrap_AnnoyIndexManhattan_load__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->load((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndexManhattan_load__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->load((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


float _wrap_AnnoyIndexManhattan_getDistance_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  int arg2 ;
  int arg3 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (float)(swig_b0)->getDistance(arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndexManhattan_getNnsByItem__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByItem(arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndexManhattan_getNnsByItem__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByItem(arg2,arg3,arg4,arg5);
  
}


void _wrap_AnnoyIndexManhattan_getNnsByVector__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByVector((float const *)arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndexManhattan_getNnsByVector__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByVector((float const *)arg2,arg3,arg4,arg5);
  
}


intgo _wrap_AnnoyIndexManhattan_getNItems_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (int)(swig_b0)->getNItems();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndexManhattan_verbose_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, bool _swig_go_1) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  bool arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->verbose(arg2);
  
}


void _wrap_AnnoyIndexManhattan_getItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, intgo _swig_go_1, GoAnnoy::AnnoyVectorFloat *_swig_go_2) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  int arg2 ;
  GoAnnoy::AnnoyVectorFloat *arg3 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getItem(arg2,arg3);
  
}


bool _wrap_AnnoyIndexManhattan_onDiskBuild_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexManhattan *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexManhattan *arg1 = (GoAnnoy::AnnoyIndexManhattan *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexManhattan **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->onDiskBuild((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


GoAnnoy::AnnoyIndexDotProduct *_wrap_new_AnnoyIndexDotProduct_annoy_db50064239c65d95(intgo _swig_go_0) {
  int arg1 ;
  GoAnnoy::AnnoyIndexDotProduct *result = 0 ;
  GoAnnoy::AnnoyIndexDotProduct *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (GoAnnoy::AnnoyIndexDotProduct *)new GoAnnoy::AnnoyIndexDotProduct(arg1);
  *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_result = (GoAnnoy::AnnoyIndexDotProduct *)result; 
  return _swig_go_result;
}


void _wrap_delete_AnnoyIndexDotProduct_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_AnnoyIndexDotProduct_addItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, intgo _swig_go_1, _goslice_ _swig_go_2) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  int arg2 ;
  float *arg3 = (float *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_2.array;
  for (int i = 0; i < _swig_go_2.len; i++) {
    w.push_back(v[i]);
  }
  arg3 = &w[0];
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->addItem(arg2,(float const *)arg3);
  
}


void _wrap_AnnoyIndexDotProduct_build_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, intgo _swig_go_1) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  int arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->build(arg2);
  
}


bool _wrap_AnnoyIndexDotProduct_save__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->save((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndexDotProduct_save__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->save((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


void _wrap_AnnoyIndexDotProduct_unload_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->unload();
  
}


bool _wrap_AnnoyIndexDotProduct_load__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, _gostring_ _swig_go_1, bool _swig_go_2) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  char *arg2 = (char *) 0 ;
  bool arg3 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  arg3 = (bool)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->load((char const *)arg2,arg3);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


bool _wrap_AnnoyIndexDotProduct_load__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->load((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


float _wrap_AnnoyIndexDotProduct_getDistance_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  int arg2 ;
  int arg3 ;
  float result;
  float _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (float)(swig_b0)->getDistance(arg2,arg3);
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndexDotProduct_getNnsByItem__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByItem(arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndexDotProduct_getNnsByItem__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, intgo _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByItem(arg2,arg3,arg4,arg5);
  
}


void _wrap_AnnoyIndexDotProduct_getNnsByVector__SWIG_0_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4, GoAnnoy::AnnoyVectorFloat *_swig_go_5) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  GoAnnoy::AnnoyVectorFloat *arg6 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  arg6 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_5; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByVector((float const *)arg2,arg3,arg4,arg5,arg6);
  
}


void _wrap_AnnoyIndexDotProduct_getNnsByVector__SWIG_1_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, _goslice_ _swig_go_1, intgo _swig_go_2, intgo _swig_go_3, GoAnnoy::AnnoyVectorInt *_swig_go_4) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  float *arg2 = (float *) 0 ;
  int arg3 ;
  int arg4 ;
  GoAnnoy::AnnoyVectorInt *arg5 = (GoAnnoy::AnnoyVectorInt *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  float *v;
  vector<float> w;
  v = (float *)_swig_go_1.array;
  for (int i = 0; i < _swig_go_1.len; i++) {
    w.push_back(v[i]);
  }
  arg2 = &w[0];
  
  arg3 = (int)_swig_go_2; 
  arg4 = (int)_swig_go_3; 
  arg5 = *(GoAnnoy::AnnoyVectorInt **)&_swig_go_4; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getNnsByVector((float const *)arg2,arg3,arg4,arg5);
  
}


intgo _wrap_AnnoyIndexDotProduct_getNItems_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  int result;
  intgo _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (int)(swig_b0)->getNItems();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_AnnoyIndexDotProduct_verbose_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, bool _swig_go_1) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  bool arg2 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  arg2 = (bool)_swig_go_1; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->verbose(arg2);
  
}


void _wrap_AnnoyIndexDotProduct_getItem_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, intgo _swig_go_1, GoAnnoy::AnnoyVectorFloat *_swig_go_2) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  int arg2 ;
  GoAnnoy::AnnoyVectorFloat *arg3 = (GoAnnoy::AnnoyVectorFloat *) 0 ;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(GoAnnoy::AnnoyVectorFloat **)&_swig_go_2; 
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  (swig_b0)->getItem(arg2,arg3);
  
}


bool _wrap_AnnoyIndexDotProduct_onDiskBuild_annoy_db50064239c65d95(GoAnnoy::AnnoyIndexDotProduct *_swig_go_0, _gostring_ _swig_go_1) {
  GoAnnoy::AnnoyIndexDotProduct *arg1 = (GoAnnoy::AnnoyIndexDotProduct *) 0 ;
  char *arg2 = (char *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(GoAnnoy::AnnoyIndexDotProduct **)&_swig_go_0; 
  
  arg2 = (char *)calloc((((_gostring_)_swig_go_1).n + 1), sizeof(char));
  strncpy(arg2, (((_gostring_)_swig_go_1).p), ((_gostring_)_swig_go_1).n);
  
  
  GoAnnoy::AnnoyIndex *swig_b0 = (GoAnnoy::AnnoyIndex *)arg1;
  result = (bool)(swig_b0)->onDiskBuild((char const *)arg2);
  _swig_go_result = result; 
  
  free(arg2);
  
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

